workflow_key: collection_curation_slack_bot
workflow_config:
  workflow_display_name: Collection Curation Slack Bot
  workflow_schema_version: '1.0'
  workflow_img_url: null
  workflow_description: null
  blocks: []
