workflow_key: foodie
workflow_config:
  workflow_display_name: Foodie
  workflow_schema_version: '1.0'
  workflow_img_url: 'https://ghexww3n55fveb5i.public.blob.vercel-storage.com/clock-rewind-tpl82PR0UFBWnD75jzlllaGm9sIB4M.svg'
  workflow_description: null

  blocks:
    - block_archetype_id: com.scoutos.input
      block_display_name: 'Town to Search?'
      block_id: inputs
      block_inputs:
        items:
          - display_name: User Message
            key: user_message
            is_optional: false
            input_type: short_text

    - block_archetype_id: com.scoutos.llm
      block_display_name: LLM
      block_id: block_a1mk1a
      block_inputs:
        model: gpt-4o
        response_format: text
        max_tokens: 300
        temperature: 0.7
        prompt_items:
          - role: user
            content: 'Where can I get food in {{inputs.user_message}}??????'
          - role: assistant
            content: 'You should respond with a list of restaurants in the area. Each restaurant should have a name, address, and rating.'
      dependencies:
        - block_id: inputs
