workflow_key: multi-language_seo_keyword_translator
workflow_config:
  workflow_display_name: Multi-Language SEO Keyword Translator
  workflow_schema_version: '1.0'
  workflow_img_url: 'https://ghexww3n55fveb5i.public.blob.vercel-storage.com/logo-JEmmypcXjOuUCLWxmAta6miJ22U1kc.png'
  workflow_description: null
  blocks:
    - block_archetype_id: com.scoutos.input
      block_config: []
      block_display_name: Keywords
      block_id: inputs
      block_inputs:
        items:
          - display_name: Keywords
            key: keywords
            default_value: 'List of Keywords to localize, comma separated'
            is_optional: false
            input_type: long_text
          - display_name: Country
            key: country
            default_value: Set this to the Country or Region in which to localize keywords for. You can add multiple countries separated by a comma.
            is_optional: false
            input_type: long_text
      trigger_config: null
      dependencies: []
    - block_archetype_id: com.scoutos.llm
      block_config: []
      block_display_name: Localize Keywords
      block_id: block_wvorc7
      block_inputs:
        model: gpt-4o
        response_format: text
        max_tokens: 1000
        temperature: 0
        items: []
        prompt_items:
          - content: |-
              You are a content localization expert. Review the provided keywords {{inputs.keywords}} and ensure they are culturally and linguistically appropriate for {{inputs.country}}. 

              Tailor them to align with local preferences, language nuances, and regional trends.

              Keep in mind these are for SEO so the keywords returned should be high ranking. 

              Return a list of keywords translated to the appropriate languge. 

              If a keyword is not appropriate let the user know and let them know why it isn't appropriate. Only do this for keywrods deemed inappropraite. 

              At the end of the message return just a list of Keywords that can easily be copied. 
            role: system
      trigger_config: null
      dependencies:
        - block_id: inputs
    - block_archetype_id: com.scoutos.text
      block_config: []
      block_display_name: List of Keywords
      block_id: block_5w5hve
      block_inputs:
        text: 'Format list of Keywords into a numbered list {{block_wvorc7.output}}'
        items: []
      trigger_config: null
      dependencies:
        - block_id: block_wvorc7
