name: Build Artifact

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Optionally trigger on release
#   release:
#     types: [created]

jobs:
  build:
    name: Build CLI Artifact
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output: scout-cli-linux
          - os: windows-latest
            output: scout-cli-windows.exe
          - os: macos-latest
            output: scout-cli-macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile CLI
        run: deno compile --allow-read --allow-write --allow-env --allow-net --output ${{ matrix.output }} mod.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

      # Only run release steps on push to main
      - name: Create Release
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        if: github.event_name == 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          name: PR #${{ github.event.pull_request.number }} Build
          tag_name: pr-${{ github.event.pull_request.number }}
          files: artifacts/**/*  # Upload all files in artifacts directory
          prerelease: true
          generate_release_notes: true
          body: |
            Test build for PR #${{ github.event.pull_request.number }}
            ${{ github.event.pull_request.html_url }}
          # name: Latest Build
          # tag_name: latest
          # files: ${{ matrix.output }}
          # prerelease: true
          # generate_release_notes: true
