name: Build Artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Optionally trigger on release
#   release:
#     types: [created]

jobs:
  build:
    name: Build CLI Artifact
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Required for creating releases
      packages: read

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output: scout-cli-linux
          - os: windows-latest
            output: scout-cli-windows.exe
          - os: macos-latest
            output: scout-cli-macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # This is a workaround to install npm dependencies
      - name: Install npm dependencies
        run: |
          deno cache --reload npm:abort-controller@3.0.0
          deno cache --reload npm:scoutos@0.7.1
        env:
          DENO_DIR: ./temp/deno-dir

      - name: Compile CLI
        run: deno compile --allow-read --allow-write --allow-env --allow-net --allow-run --output ${{ matrix.output }} mod.ts
        env:
          DENO_DIR: ./temp/deno-dir

      # Add debug steps
      - name: Debug - List Files
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Output file location:"
          find . -name "${{ matrix.output }}"
          echo "Artifact server path contents:"
          ls -la /tmp/artifacts || echo "No artifacts directory yet"

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.output }}
      #     path: ${{ matrix.output }}

  release:
    name: Release Artifact
    needs: build
    # runs-on: ubuntu-latest / unknown prop
    # uses: actions/create-release@v4 / unknown
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.sha }}
          tag_name: release-${{ github.sha }}
          files: |
            artifacts/scout-cli-linux/scout-cli-linux
            artifacts/scout-cli-windows.exe/scout-cli-windows.exe
            artifacts/scout-cli-macos/scout-cli-macos
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Release URL
        run: |
          echo "Release was created at: https://github.com/${{ github.repository }}/releases/tag/release-${{ github.sha }}"
          echo "Artifacts should be available at: https://github.com/${{ github.repository }}/releases/download/release-${{ github.sha }}/"
